version: "3.8"
# x-aws-loadbalancer: "ecs-LoadBala-aNc8nTIegD6M"
services:
  blogui:
    container_name: blogui
    image: naresh546/blog-site-ui:aws
    ports:
      - "80:80"
    networks:
      - ui-blogsite
    environment:
      - REACT_APP_TOKEN="Token value set in environment variables"
      - REACT_APP_TOKEN_2="Extra token variables"
networks:
  ui-blogsite:
